language: android
env:
    global:
    - TERM=dumb
    matrix:
    - EMULATOR_VERSION=19
    - EMULATOR_VERSION=18
    - EMULATOR_VERSION=17
    - EMULATOR_VERSION=16
    - EMULATOR_VERSION=15
    - EMULATOR_VERSION=10
    - EMULATOR_VERSION=8

script: ./ci.sh travis

